services:
  - type: web
    name: studysmart-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_HTTP_PORTS
        value: "8080"
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "1"
      - key: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
        value: "false"
      - key: ConnectionStrings__Conn
        sync: false
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: StudySmartAPI
      - key: Jwt__Audience
        value: StudySmartClient
      - key: AllowedOrigins
        value: "*"
