// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactApp1.Server.Models;

#nullable disable

namespace ReactApp1.Server.Migrations
{
    [DbContext(typeof(StudentdbContext))]
    [Migration("20260405200849_AddExamQuestions")]
    partial class AddExamQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReactApp1.Server.Models.AnalyticsDaily", b =>
                {
                    b.Property<int>("AnalyticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("analytics_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalyticsId"));

                    b.Property<int?>("CompletedTasks")
                        .HasColumnType("int")
                        .HasColumnName("completed_tasks");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("StudyMinutes")
                        .HasColumnType("int")
                        .HasColumnName("study_minutes");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("AnalyticsId")
                        .HasName("PK__Analytic__D5DC3DE1ABD258CA");

                    b.HasIndex("UserId");

                    b.ToTable("Analytics_Daily", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("announcement_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.HasKey("AnnouncementId")
                        .HasName("PK__Announce__C640A82D367A1503");

                    b.HasIndex("AdminId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Assignme__DA89181467C232C0");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MentorId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.AssignmentSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_path");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("SubmissionId")
                        .HasName("PK__Assignme__9B535595F8FEE8A6");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Assignment_Submissions", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.CalendarEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("EventType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("EventId")
                        .HasName("PK__Calendar__2370F7270ACF0B8B");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Calendar_Events", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.DailyReflection", b =>
                {
                    b.Property<int>("ReflectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reflection_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReflectionId"));

                    b.Property<string>("Challenges")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("challenges");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("ImprovementPlan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("improvement_plan");

                    b.Property<string>("Mood")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("mood");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("ReflectionId")
                        .HasName("PK__Daily_Re__D8E1913AA540B17D");

                    b.HasIndex("StudentId");

                    b.ToTable("Daily_Reflection", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("difficulty_level");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("subject");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("ExamId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Exams", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ExamAnswer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("answer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("DescriptiveAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descriptive_answer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("score");

                    b.Property<string>("SelectedOption")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("selected_option");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("ExamAnswers", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ExamAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("AssignedBy")
                        .HasColumnType("int")
                        .HasColumnName("assigned_by");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamAssignments", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ExamQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correct_answer");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("difficulty_level");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<string>("OptionA")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option_a");

                    b.Property<string>("OptionB")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option_b");

                    b.Property<string>("OptionC")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option_c");

                    b.Property<string>("OptionD")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option_d");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("QuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamQuestions", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ExamSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<decimal?>("AiScore")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("ai_score");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    b.Property<int?>("CheatingViolations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("cheating_violations");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("score");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.HasKey("SubmissionId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamSubmissions", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Feedback1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feedback");

                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__7A6B2B8C33E38C9B");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MentorId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_path");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("MaterialId")
                        .HasName("PK__Material__6BFE1D28B6ABCEE3");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Mentor", b =>
                {
                    b.Property<int>("MentorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MentorId"));

                    b.Property<bool?>("AvailabilityStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("availability_status");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<int?>("MaxStudents")
                        .HasColumnType("int")
                        .HasColumnName("max_students");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("MentorId")
                        .HasName("PK__Mentors__E5D27EF37A466080");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("availability_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("AvailabilityId")
                        .HasName("PK__Mentor_A__86E3A80175419AE7");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MentorId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Mentor_Availability", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorPerformance", b =>
                {
                    b.Property<int>("MentorPerfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mentor_perf_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MentorPerfId"));

                    b.Property<decimal?>("AvgStudentProductivity")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("avg_student_productivity");

                    b.Property<decimal?>("AvgStudentRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("avg_student_rating");

                    b.Property<int?>("FeedbackCount")
                        .HasColumnType("int")
                        .HasColumnName("feedback_count");

                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<DateOnly?>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly?>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<int?>("StudentsHandled")
                        .HasColumnType("int")
                        .HasColumnName("students_handled");

                    b.HasKey("MentorPerfId")
                        .HasName("PK__Mentor_P__564C58C5911ED805");

                    b.HasIndex("MentorId");

                    b.ToTable("Mentor_Performance", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<string>("RequestStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("request_status");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("responded_at");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("RequestId")
                        .HasName("PK__Mentor_R__18D3B90F2AAB317F");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MentorId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("SkillId");

                    b.HasIndex("StudentId");

                    b.ToTable("Mentor_Requests", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("EndTime")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("end_time");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("meeting_link");

                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ScheduledDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_datetime");

                    b.Property<string>("SessionDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("session_date");

                    b.Property<string>("SessionStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Scheduled")
                        .HasColumnName("session_status");

                    b.Property<string>("StartTime")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("start_time");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("SessionId")
                        .HasName("PK__Mentor_S__69B13FDC9C8E5C11");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MentorId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("Mentor_Sessions", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorSkill", b =>
                {
                    b.Property<int>("MentorSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mentor_skill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MentorSkillId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<string>("ProficiencyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("proficiency_level");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.HasKey("MentorSkillId")
                        .HasName("PK__Mentor_S__90A45BD5305BD820");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MentorId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("SkillId");

                    b.ToTable("Mentor_Skills", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PK__Mentor_S__3213E83F3614C67E");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MentorId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("Mentor_Student", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("note_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NoteId")
                        .HasName("PK__Notes__CEDD0FA47B0D9DD5");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Notification", b =>
                {
                    b.Property<int>("NotifyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notify_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotifyId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("message");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotifyId")
                        .HasName("PK__Notifica__DD351C9692495855");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.PerformanceReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<decimal>("ProductivityScore")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("productivity_score");

                    b.Property<DateOnly?>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReportId")
                        .HasName("PK__Performa__779B7C587A74BA95");

                    b.HasIndex("UserId");

                    b.ToTable("Performance_Report", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Course")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("course");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<int?>("Semester")
                        .HasColumnType("int")
                        .HasColumnName("semester");

                    b.Property<string>("University")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("university");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__2A33069A72758BB4");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.StudentGoal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("goal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("GoalStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("goal_status");

                    b.Property<string>("GoalTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("goal_title");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int?>("TargetHours")
                        .HasColumnType("int")
                        .HasColumnName("target_hours");

                    b.Property<int?>("TargetTasks")
                        .HasColumnType("int")
                        .HasColumnName("target_tasks");

                    b.HasKey("GoalId")
                        .HasName("PK__Student___76679A24749B0B3A");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("Student_Goals", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.StudentMentorFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2, 1)")
                        .HasColumnName("rating");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Student___7A6B2B8C8B8469CD");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MentorId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("Student_Mentor_Feedback", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.StudySession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int?>("DurationMin")
                        .HasColumnType("int")
                        .HasColumnName("duration_min");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<string>("Subject")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("subject");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("PK__Study_Se__69B13FDC3892D0A0");

                    b.HasIndex("UserId");

                    b.ToTable("Study_Sessions", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.SubjectsSkill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("skill_name");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("skill_type");

                    b.HasKey("SkillId")
                        .HasName("PK__Subjects__FBBA83799463EB5B");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Subjects_Skills", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TaskId")
                        .HasName("PK__Tasks__0492148DE89F3958");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370F60A8A2F1");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E616429FBAA00")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.AnalyticsDaily", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "User")
                        .WithMany("AnalyticsDailies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Analytics__user___236943A5");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Announcement", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "Admin")
                        .WithMany("AnnouncementAdmins")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("FK__Announcem__admin__09A971A2");

                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("AnnouncementCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Announcem__creat__0A9D95DB");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("AnnouncementModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Announcem__modif__0B91BA14");

                    b.Navigation("Admin");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Assignment", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("AssignmentCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Assignmen__creat__797309D9");

                    b.HasOne("ReactApp1.Server.Models.Mentor", "Mentor")
                        .WithMany("Assignments")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__Assignmen__mento__787EE5A0");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("AssignmentModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Assignmen__modif__7A672E12");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Mentor");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.AssignmentSubmission", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Assignment", "Assignment")
                        .WithMany("AssignmentSubmissions")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Assignmen__assig__7E37BEF6");

                    b.HasOne("ReactApp1.Server.Models.Student", "Student")
                        .WithMany("AssignmentSubmissions")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Assignmen__stude__7F2BE32F");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.CalendarEvent", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("CalendarEventCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Calendar___creat__1F98B2C1");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("CalendarEventModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Calendar___modif__208CD6FA");

                    b.HasOne("ReactApp1.Server.Models.User", "User")
                        .WithMany("CalendarEventUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Calendar___user___1EA48E88");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.DailyReflection", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Student", "Student")
                        .WithMany("DailyReflections")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Daily_Ref__stude__1AD3FDA4");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Exam", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Mentor", "Mentor")
                        .WithMany("Exams")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Mentors");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ExamAnswer", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.ExamQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAnswers_Questions");

                    b.HasOne("ReactApp1.Server.Models.ExamSubmission", "Submission")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAnswers_Submissions");

                    b.Navigation("Question");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ExamAssignment", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .IsRequired()
                        .HasConstraintName("FK_ExamAssignments_Mentors");

                    b.HasOne("ReactApp1.Server.Models.Exam", "Exam")
                        .WithMany("ExamAssignments")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamAssignments_Exams");

                    b.HasOne("ReactApp1.Server.Models.Student", "Student")
                        .WithMany("ExamAssignments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_ExamAssignments_Students");

                    b.Navigation("Exam");

                    b.Navigation("Mentor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ExamQuestion", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamQuestions_Exams");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ExamSubmission", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.ExamAssignment", "ExamAssignment")
                        .WithMany("ExamSubmissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamSubmissions_ExamAssignments");

                    b.HasOne("ReactApp1.Server.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_ExamSubmissions_Students");

                    b.Navigation("ExamAssignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Feedback", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("FeedbackCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Feedback__create__04E4BC85");

                    b.HasOne("ReactApp1.Server.Models.Mentor", "Mentor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__mentor__02FC7413");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("FeedbackModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Feedback__modifi__05D8E0BE");

                    b.HasOne("ReactApp1.Server.Models.Student", "Student")
                        .WithMany("Feedbacks")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__studen__03F0984C");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Mentor");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Material", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("MaterialCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Materials__creat__6FE99F9F");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("MaterialModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Materials__modif__70DDC3D8");

                    b.HasOne("ReactApp1.Server.Models.User", "User")
                        .WithMany("MaterialUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Materials__user___6EF57B66");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Mentor", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("MentorCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Mentors__created__32E0915F");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("MentorModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Mentors__modifie__33D4B598");

                    b.HasOne("ReactApp1.Server.Models.User", "User")
                        .WithMany("MentorUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentors__user_id__31EC6D26");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorAvailability", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("MentorAvailabilityCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Mentor_Av__creat__5629CD9C");

                    b.HasOne("ReactApp1.Server.Models.Mentor", "Mentor")
                        .WithMany("MentorAvailabilities")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentor_Av__mento__5535A963");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("MentorAvailabilityModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Mentor_Av__modif__571DF1D5");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Mentor");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorPerformance", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Mentor", "Mentor")
                        .WithMany("MentorPerformances")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentor_Pe__mento__29221CFB");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorRequest", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("MentorRequestCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Mentor_Re__creat__48CFD27E");

                    b.HasOne("ReactApp1.Server.Models.Mentor", "Mentor")
                        .WithMany("MentorRequests")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentor_Re__mento__46E78A0C");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("MentorRequestModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Mentor_Re__modif__49C3F6B7");

                    b.HasOne("ReactApp1.Server.Models.SubjectsSkill", "Skill")
                        .WithMany("MentorRequests")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentor_Re__skill__47DBAE45");

                    b.HasOne("ReactApp1.Server.Models.Student", "Student")
                        .WithMany("MentorRequests")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentor_Re__stude__45F365D3");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Mentor");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Skill");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorSession", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("MentorSessionCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Mentor_Se__creat__5DCAEF64");

                    b.HasOne("ReactApp1.Server.Models.Mentor", "Mentor")
                        .WithMany("MentorSessions")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentor_Se__mento__5BE2A6F2");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("MentorSessionModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Mentor_Se__modif__5EBF139D");

                    b.HasOne("ReactApp1.Server.Models.Student", "Student")
                        .WithMany("MentorSessions")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentor_Se__stude__5CD6CB2B");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Mentor");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorSkill", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("MentorSkillCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Mentor_Sk__creat__3F466844");

                    b.HasOne("ReactApp1.Server.Models.Mentor", "Mentor")
                        .WithMany("MentorSkills")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentor_Sk__mento__3D5E1FD2");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("MentorSkillModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Mentor_Sk__modif__403A8C7D");

                    b.HasOne("ReactApp1.Server.Models.SubjectsSkill", "Skill")
                        .WithMany("MentorSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentor_Sk__skill__3E52440B");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Mentor");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.MentorStudent", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("MentorStudentCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Mentor_St__creat__4F7CD00D");

                    b.HasOne("ReactApp1.Server.Models.Mentor", "Mentor")
                        .WithMany("MentorStudents")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentor_St__mento__4D94879B");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("MentorStudentModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Mentor_St__modif__5070F446");

                    b.HasOne("ReactApp1.Server.Models.Student", "Student")
                        .WithMany("MentorStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Mentor_St__stude__4E88ABD4");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Mentor");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Note", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notes__user_id__6B24EA82");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Notification", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__user___10566F31");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.PerformanceReport", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "User")
                        .WithMany("PerformanceReports")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Performan__user___2645B050");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Student", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("StudentCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Students_CreatedBy");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("StudentModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK_Students_ModifiedBy");

                    b.HasOne("ReactApp1.Server.Models.User", "User")
                        .WithMany("StudentUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Students__user_i__2C3393D0");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.StudentGoal", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("StudentGoalCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Student_G__creat__160F4887");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("StudentGoalModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Student_G__modif__17036CC0");

                    b.HasOne("ReactApp1.Server.Models.Student", "Student")
                        .WithMany("StudentGoals")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Student_G__stude__151B244E");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.StudentMentorFeedback", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("StudentMentorFeedbackCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Student_M__creat__2EDAF651");

                    b.HasOne("ReactApp1.Server.Models.Mentor", "Mentor")
                        .WithMany("StudentMentorFeedbacks")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__Student_M__mento__2DE6D218");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("StudentMentorFeedbackModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Student_M__modif__2FCF1A8A");

                    b.HasOne("ReactApp1.Server.Models.Student", "Student")
                        .WithMany("StudentMentorFeedbacks")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Student_M__stude__2CF2ADDF");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Mentor");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.StudySession", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "User")
                        .WithMany("StudySessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Study_Ses__user___68487DD7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.SubjectsSkill", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("SubjectsSkillCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Subjects___creat__38996AB5");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("SubjectsSkillModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Subjects___modif__398D8EEE");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Task", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("TaskCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Tasks__created_b__6477ECF3");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("TaskModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Tasks__modified___656C112C");

                    b.HasOne("ReactApp1.Server.Models.User", "User")
                        .WithMany("TaskUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Tasks__user_id__6383C8BA");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.User", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.User", "CreatedByNavigation")
                        .WithMany("InverseCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Users__created_b__286302EC");

                    b.HasOne("ReactApp1.Server.Models.User", "ModifiedByNavigation")
                        .WithMany("InverseModifiedByNavigation")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Users__modified___29572725");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Assignment", b =>
                {
                    b.Navigation("AssignmentSubmissions");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Exam", b =>
                {
                    b.Navigation("ExamAssignments");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ExamAssignment", b =>
                {
                    b.Navigation("ExamSubmissions");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ExamSubmission", b =>
                {
                    b.Navigation("ExamAnswers");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Mentor", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Exams");

                    b.Navigation("Feedbacks");

                    b.Navigation("MentorAvailabilities");

                    b.Navigation("MentorPerformances");

                    b.Navigation("MentorRequests");

                    b.Navigation("MentorSessions");

                    b.Navigation("MentorSkills");

                    b.Navigation("MentorStudents");

                    b.Navigation("StudentMentorFeedbacks");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Student", b =>
                {
                    b.Navigation("AssignmentSubmissions");

                    b.Navigation("DailyReflections");

                    b.Navigation("ExamAssignments");

                    b.Navigation("Feedbacks");

                    b.Navigation("MentorRequests");

                    b.Navigation("MentorSessions");

                    b.Navigation("MentorStudents");

                    b.Navigation("StudentGoals");

                    b.Navigation("StudentMentorFeedbacks");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.SubjectsSkill", b =>
                {
                    b.Navigation("MentorRequests");

                    b.Navigation("MentorSkills");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.User", b =>
                {
                    b.Navigation("AnalyticsDailies");

                    b.Navigation("AnnouncementAdmins");

                    b.Navigation("AnnouncementCreatedByNavigations");

                    b.Navigation("AnnouncementModifiedByNavigations");

                    b.Navigation("AssignmentCreatedByNavigations");

                    b.Navigation("AssignmentModifiedByNavigations");

                    b.Navigation("CalendarEventCreatedByNavigations");

                    b.Navigation("CalendarEventModifiedByNavigations");

                    b.Navigation("CalendarEventUsers");

                    b.Navigation("FeedbackCreatedByNavigations");

                    b.Navigation("FeedbackModifiedByNavigations");

                    b.Navigation("InverseCreatedByNavigation");

                    b.Navigation("InverseModifiedByNavigation");

                    b.Navigation("MaterialCreatedByNavigations");

                    b.Navigation("MaterialModifiedByNavigations");

                    b.Navigation("MaterialUsers");

                    b.Navigation("MentorAvailabilityCreatedByNavigations");

                    b.Navigation("MentorAvailabilityModifiedByNavigations");

                    b.Navigation("MentorCreatedByNavigations");

                    b.Navigation("MentorModifiedByNavigations");

                    b.Navigation("MentorRequestCreatedByNavigations");

                    b.Navigation("MentorRequestModifiedByNavigations");

                    b.Navigation("MentorSessionCreatedByNavigations");

                    b.Navigation("MentorSessionModifiedByNavigations");

                    b.Navigation("MentorSkillCreatedByNavigations");

                    b.Navigation("MentorSkillModifiedByNavigations");

                    b.Navigation("MentorStudentCreatedByNavigations");

                    b.Navigation("MentorStudentModifiedByNavigations");

                    b.Navigation("MentorUsers");

                    b.Navigation("Notes");

                    b.Navigation("Notifications");

                    b.Navigation("PerformanceReports");

                    b.Navigation("StudentCreatedByNavigations");

                    b.Navigation("StudentGoalCreatedByNavigations");

                    b.Navigation("StudentGoalModifiedByNavigations");

                    b.Navigation("StudentMentorFeedbackCreatedByNavigations");

                    b.Navigation("StudentMentorFeedbackModifiedByNavigations");

                    b.Navigation("StudentModifiedByNavigations");

                    b.Navigation("StudentUsers");

                    b.Navigation("StudySessions");

                    b.Navigation("SubjectsSkillCreatedByNavigations");

                    b.Navigation("SubjectsSkillModifiedByNavigations");

                    b.Navigation("TaskCreatedByNavigations");

                    b.Navigation("TaskModifiedByNavigations");

                    b.Navigation("TaskUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
